


server:
  port: 8082


config:
  api-qr-url: http://localhost:8080/1/generator/qr
  qr-content-base: http://192.168.1.108:8081/?tranId=

version: 1


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true